#ifndef PROXY_LOG_HH
#define PROXY_LOG_HH

#include "soil/Log.hh"

#define PROXY_LOG_INIT(x) SOIL_LOG_INIT(x)

#define PROXY_TRACE SOIL_TRACE
#define PROXY_DEBUG SOIL_DEBUG
#define PROXY_INFO  SOIL_INFO
#define PROXY_WARNING SOIL_WARNING
#define PROXY_ERROR SOIL_ERROR
#define PROXY_FATAL SOIL_FATAL
#define PROXY_PDU SOIL_PDU
#define PROXY_CUSTOM SOIL_CUSTOM


#endif

