#ifndef TEXT_LOG_HH
#define TEXT_LOG_HH

#include "soil/Log.hh"

#define TEXT_LOG_INIT(x) SOIL_LOG_INIT(x)

#define TEXT_TRACE SOIL_TRACE
#define TEXT_DEBUG SOIL_DEBUG
#define TEXT_INFO  SOIL_INFO
#define TEXT_WARNING SOIL_WARNING
#define TEXT_ERROR SOIL_ERROR
#define TEXT_FATAL SOIL_FATAL
#define TEXT_PDU SOIL_PDU
#define TEXT_CUSTOM SOIL_CUSTOM


#endif

